name: Test Neovim Configuration

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 0"  # Run weekly on Sunday at midnight

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build gettext cmake unzip curl git

    - name: Install latest Neovim
      run: |
        git clone https://github.com/neovim/neovim
        cd neovim
        git checkout stable
        make CMAKE_BUILD_TYPE=RelWithDebInfo
        sudo make install
        cd ..
        nvim --version

    - name: Run test suite
      run: ./scripts/test-nvim-config.sh
